version: '2.1'
services:
  event-detection:
    cap_add:
    - SYS_PTRACE
    image: event-detection
    container_name: event-detection
    healthcheck:
      test: ["CMD","/healthcheck.sh"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - default
    ports:
     - "8081:8080"
    environment:
        - "constraint:node==slave3"
        - CASSANDRA_IP=
        - CASSANDRA_PORT=
        - CASSANDRA_KEYSPACE=
        - CASSANDRA_CLUSTER=
        - TWITTER_KEY=
        - TWITTER_KEYSEC=
        - TWITTER_TOK=
        - TWITTER_TOKSEC=
        - EXTRACTOR_AUTH=
    depends_on:
      cassandra-cluster-2:
        condition: service_healthy
    depends_on:
      lookupservice:
        condition: service_healthy
    depends_on:
      geotriples:
        condition: service_healthy
